version: '3'

services:

  mysql-server:
    image: mysql:latest
    restart: always
    env_file:
      ./credentials.env
    ports:
      - 3306:3306
    volumes:
      - ./persistent_db:/var/lib/mysql  # persist when container is stopped!
    container_name: 140a-mysql-db

  rest-server:
    build:
      context: ./server
    ports:
      - 6543:6543
    env_file:
      ./credentials.env
    volumes:
      - ./server/src:/app
    container_name: 140a-rest-server

volumes:
  persistent_db:
